# Configuration file example
duration: 10  # in seconds
overlap: 0.2  # overlap of the chunks in %
desired_fs: 44100  # desired sampling rate
channel: 2  # number of channels
log: True  # whether to log or not
color: 'blue'  # color setting


wavs_folder: '/storage/Imagine_UC6_new/DATA/data_per_station_4_updated_metadata_extra_filter-window-4'
d_valid_path: r"/srv/CLAP/ds_split-CLAP/val.txt"
d_train_path: r"/srv/CLAP/ds_split-CLAP/train.txt"
d_test_path: r"/srv/CLAP/ds_split-CLAP/test.txt"
dataset_folder: '/path/to/dataset'
annotations_file: '/path/to/annotations.csv'

# Parameters for audio processing
nfft: 1024  # number of FFT points
win_len: 512  # window length
hop_ratio: 4  # hop ratio
normalization_style: 'mean_std'  # normalization style

# Optional parameters
min_duration: 0  # minimum duration, if not provided, it will be calculated based on nfft and desired_fs
max_duration: 10  # maximum duration, if not provided, it will be set to half of the overall duration
MIN_SNR: 10  # minimum signal-to-noise ratio

# Additional settings
blocksize: 441000  # block size based on duration and desired sampling rate
